name: flake-check
run-name: Check nix flake

on: [pull_request]

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Check flake
        run: nix flake check
