user: ENC[AES256_GCM,data:ZXlR+0odvX6JI0UoEI2KEdC+L6eftDuDQg4Erc6x8xIRZ4iKhU2tZziNXQ1w4c1ouAn8fZ0p1/LRULoP+/62UV6opaDPF2laaA==,iv:syv7HqxZaQrnj5TF56fKS18trR71wdF02mkY9A9dBqs=,tag:1CHjoy8bv3fv9sz8hxlBsg==,type:str]
sops:
    age:
        - recipient: age1r7u3v4csrvqqcxw0u0mgz22qa63ft3sscdl8yan2ge4k7trtacjqy0w7uf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmc3dYbHllY3A3VE9tY3M0
            L29DZzVZcmhSbHRaNE5obWdzUWtjWU9zYVJjCmQrT09QMkd5YmRtbDcyOGRFbVA0
            UERNWTEzMTlwbC9jU0FvYTB3Vmx6eTgKLS0tIGIyODdwMlMxcXZ1SmF6dlBxNTRi
            d3pNM0s2UlFwaW9wM3k4V1pCOXhTeWsKjT+yx4t4kMEGgMJe+xWtv/YQksc6fN3R
            IEJ2S3aksn9iWQRqnovf+9ez25MGvJMk+gFHmLA35e8QYKPYPxajwA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ate9csmpldp5596mkfs4lklj9338ahgqd2lxtv757wp8xey75mq9e5gvp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTenYwai9JVUo4RWZqY3dY
            OERnK0lnOW9uUzBHeXpGaE1yL1FRSVJpUWlFCndyYUU0RHZVL1pYV1NRRHZ1RTFI
            c1hzcHlCcmFOYWdFekp0Rm55aXlkcE0KLS0tIEh4SFVjSmpFOHFOQ0d3VGUxU3dX
            ZUxwMVkvR1k2OXp0R3M1TEw0aWdGeTQKvzD3rLsGZAQxE5xc/6lJkawqQ0Lf9gKC
            UX7TA8fNi0mvtHmoEWCURa/GdLbmHXMg7eMq/Y2MpUsYHkM3RL2YqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-27T17:26:51Z"
    mac: ENC[AES256_GCM,data:5wG5YBsxWtYXmfi9eiY5I6RgZDQuEj+VvlsiuyeG4oVkevT5wBnjWw0xbwNLazIkiCJiGrDXaLdmFvcXz6+7A36E9nkuPhFX8kKQIReWzs6jHubEu86DWo0Bh4gUNXen2yN/uqUSyhd5cUYvAgE0DIZJ8pSb2qSzGfFf/kc80j0=,iv:GUycPTX/WSs5fAfXH+y+DmxGck9CmyWnp67eCQF9bbU=,tag:Qem0o/zb+UPvwAShQHEddg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
